language: node_js
node_js:
- '8'
script:
- npm test
- npm run build:js
- npm run webpack
deploy:
  provider: heroku
  api_key:
    secure: tlDbPZ6cQVP9YI90rFkjzWp0dNo3k1scTXBB60T1s9Z6li3eUVAZqgeVXAYjNq9TSA54aWFvgX7HsIDCinfLH/g6TPBIanUQ3a4RRdB6IdT5xZ5cGQinzIJngE8i96VOL1l0vjCFbdgJtcO73DQUs0URR6duSbLtuFB624XVrkt8uIXazECHDYnDL0m2Fc4/9VeOPk6zHUSpGT54WjfS90aWtoOJkTsk59xKc2ykE0ddl9Ws+OZbs8d6wbN6bo1jrK/3Ldc97hvq56iwIevK4uySYP4hNECG8izNDSy9R8G7djz+rvjcysEXiQ/V/8vvsEEFH93pcF+PTUrRDwhxevLQVjGdnNI5Iy6nj0XEOQoxNTvRZkzazI0NL7FOFOvX5SZKigUR6SamfaU5bbmzpvTH0m/DCGd7Sm3XQX+DJAuIadmqZedrpQSctrbqzl6vtkwZZZ8npB+H4KSmU56Q883OZYhr5M8airsPvO58crmNd7TldMF8RzZ/4uky5yugYnCtvCF08BTFGzMWuRmBEP1PIUtvqXUAf3Bmh5R8TB6nqrcDLaZ0upNQgN9mSm7vXeX/JxcKX0yGGFg0r2CY6cnk7Qeh2OKyLJ7D2ZMYrd2P2WuLZL77GrOpAzR1QYlnvLqGTXfXUHQkxtuf8mtxVpQt9eISXOgv7GVj1uheY5I=
  app:
    master: imperium-incursion-waitlist
    development: incursion-waitlist-staging
  skip_cleanup: true
