language: node_js
node_js:
- '8'
script:
- npm test
- npm run build:js
deploy:
  provider: heroku
  api_key:
    secure: fo/t4HHc8t+xFEdVuK/ulazPl5KeHoNOuySgDppq+uLx9Z5UJaTSqvBLhPSf8XHE72wdayokxcgwMG5DEC6K9/pYNKLuhZ+3sPEXN0mPYF5eDtji6ZwE9VyurmK/+6ymXBfXLPGGyELnJMJSVU5VXkXdStlJSiciuuh5zpZrSpJc1rKJQWTidwh/bY7seThiPpV31NjVWRjmaoop2RIqt3M+9akMXgF9F2d6FCg8nYMG/JMW/f712fvDHHF3g8fxQz61zKZOxJxCRm1xIPcZ7d08OXKo4oFhnKG7oWt8WeuW3qAmJj/Fbm9iKNdQoEfRekGeoiJoxBrkUSZTE9f73rO2KwAwYf1HkKxuGoePwOeMP0Pbb91LQ6dYnU3rVcTC89CQD6Inx+j88yLfN9fZgp1R+MC6y3BH+5Nmbq0TjNqYYme62VAeqtheBbRKvzWsB6crFAtcm1N+/bwCWKaVp+m4guKpUlpxFxU0/HcFmj5b43rUvWM0FmZqCJV2hcK5lLlEB7S6MPJF4f42nxZsZd+wNKk1fShDKFM9lGi3oW/9vragbxcVI8Kr+yflZopJTm+nAcKKN4oo8H2ufVae0962ootfr2cK+dbi1CmtrMqXVMqExPH2X8xzp9yd8yn3z6XkeP5VAiC9NuQwDNfmo5JwerxRO9qkUW0Ga42np8k=
  app:
    master: imperium-incursion-waitlist
    development: incursion-waitlist-staging
  skip_cleanup: true
