language: node_js
node_js:
- '8'
script:
- npm test
- npm run build:js
- npm run webpack
deploy:
  provider: heroku
  api_key:
    secure: DuiyzaR3Nx0VpglNp1ZW/YnOl4rYcyErL9kFvzy27bROjmjKEQjgt3NLCtHfOOBO36wU/My7bzTlZ7iMeTB2AuZQwb4DFKxgZfdE8fXKamMylvhqxiIOIqP8GqkkGGkGoWXClSGTTIwhMFsdSUdfgQHttcFro3WDmEv40gk5aouHdYEWQh8B7D8D/HgOvkjcE36gsHrru8upWCU6M3rgYxe6+Y++sEYy89Oqgxp6kLROnnixfCK3qabxMPeIT8hUiDXQRBHQ2UhQ+ppA8WUbF5/uKJTw3BtqMP3Mrcx2bbZZ/Id5mGfovCm9fNfioDeARgNLjBJJvc5mSA2Yt9QWqSTWrDUB8LbkQZV5xoULpsq9WdbKU9YnV62xR1QOPRYMncc23JXBTm9L5Zx+rDbGeJDUcQtwrxBNtMQ1hv3UXbG3VBhx/PPvsJpOh5Hq3EzyqpItST3pS+LswDnhZ8RkSt2mfgeDXBgHLIykuwqw5JVifPrlaSrn37VEXL2zfeShb1I5NpBwI1BqMEeMQRi235xqgZnK1HM426r0Syg4S/5NkVxXOIuFg8sgTDm7xM2wBZg0ogEzj6rTvuX/3CvnWyfOFIClxfL/qjq4/sNkDiLWOl0cyT5YFbqV4cCzN+Zv5FYwNie1Gn2IlTh9gxkEnaM5I4iN9KU9gZx1oGXVhXc=
  app:
    master: imperium-incursion-waitlist
    development: incursion-waitlist-staging
  skip_cleanup: true
